spring.application.name=portifolio

portifolio.secretkey= ${PORTIFOLIO_PASSKEY}
portifolio.issuer=${PORTIFOLIO_ISSUER}

cloudnary.secret.name=${CLOUDNARY_USER}
cloudnary.secret.api-key=${CLOUDNARY_API_KEY}
cloudnary.secret.api-secret=${CLOUDNARY_API_SECRET}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect